### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by RandyParedis** [RandyParedis/IR-1920#1]
Below, a list of all items that are yet to do for the project. New items may be added and items that are done may be checked off.

- [x] Queries in orde?  --  @joostatsooj 
  - [x] Queries opgesteld
  - [x] Suggestions up-to-date brengen met queries
  - [x] Manueel labelen
  - [x] Verkrijgen van labeling uit code
- [x] PR/ROC curves -- @RandyParedis 
  - [x] Remove AUC
  - [x] Parse result documents
  - [x] Precision@k / (Recall@k)
- [x] Rocchio algorithm
  - [Implementation](https://github.com/gtsherman/lucene/blob/master/src/main/java/org/retrievable/lucene/searching/expansion/Rocchio.java)
  - [Example Main Class](https://github.com/gtsherman/lucene/blob/master/src/main/java/org/retrievable/lucene/searching/Searcher.java)
- [ ] Paper herschrijven
